version: '3.3'
services:
  service:
    container_name: challenge
    image: challenge:latest
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      - db
    env_file:
      - docker-env.env
  db:
    container_name: postgres
    image: postgres:12.3-alpine
    ports:
      - '5432:5432'
    env_file:
      - docker-env.env
